config/routes.rb
Rails.application.routes.draw do
  root "tests#index"

  devise_for :users, path: :gurus,
                               path_names: { sign_in: :login, sign_out: :logout }

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :show
  end
end

app/models/question.rb
class Question < ApplicationRecord
  MAX_NUMBER_OF_ANSWERS = 4

  validates :body, presence: true

  has_many :gists
  has_many :answers
  belongs_to :test, optional: true

  def num_of_answers
    answers.count
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  PASSAGE_PERCENT = 85.0

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_next_question, on: %i[create update]

  scope :exclude_tests, ->(test_ids) { where("test_id NOT IN (?)", test_ids.is_a?(Array) ? test_ids : [test_ids]) }
  scope :for_tests, ->(test_ids) { where(test_id: test_ids.is_a?(Array) ? test_ids : [test_ids]) }
  scope :exclude, ->(passage_ids) { where("id NOT IN (?)", passage_ids.is_a?(Array) ? passage_ids : [passage_ids]) }
  scope :completed, -> { where(current_question: nil) }
  scope :passed, -> { completed.where("score >= ?", PASSAGE_PERCENT) }

  def accept!(answer_ids)
    if out_of_time?
      finish_test!
    else
      self.correct_questions += 1 if correct_answer?(answer_ids)
      self.score = score
    end
    save!
  end

  def completed?
    current_question.nil?
  end

  def passed?
    score >= PASSAGE_PERCENT
  end

  def score
    (correct_questions / questions_number.to_f) * 100
  end

  def questions_number
    test.questions.count
  end

  def current_question_number
    test
      .questions
      .where("id <= ?", current_question.id)
      .count
  end

  def out_of_time?
    limited_in_time? && time_left.negative?
  end

  def limited_in_time?
    test.time_limit > 0
  end

  def time_left
    return test.time_limit unless created_at

    finish_before = created_at + test.time_limit.minute
    finish_before - Time.current
  end

  def to_s
    "#{score} %"
  end

  def finish_test!
    self.current_question = nil
  end

  private

  def correct_answer?(answer_ids)
    return false if answer_ids.nil? || answer_ids.empty?
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test
      .questions
      .where("id > ?", current_question || 0)
      .order(id: :ASC)
      .first
  end

  def before_validation_set_next_question
    self.current_question = next_question if !out_of_time? && test.present?
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show
  end

  def result
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      BadgesService.new(current_user).give_badges!(@test_passage)
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    @question = @test_passage.current_question
    result = GistQuestionService.new(@question).call

    if result[:success]
      current_user.gists.create(gist_params(result))
      flash_options = { notice: t('.success', gist_url: result[:url]), flash: { html_safe: true } }
    else
      flash_options = { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  private

  def gist_params(result)
    { url: result[:url], question_id: @question.id }
  end

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def timer(test_passage)
    return "" unless test_passage.limited_in_time?
    content_tag :div do
      content_tag(:span, t(".time_left") << ": ") +
      content_tag(:span, "", class: "timer", data: { time_left: test_passage.time_left })
    end
  end
end

app/views/test_passages/result.html.erb
<h1><%= t(".header", title: @test_passage.test.title) %></h1>

<p>
  <% if @test_passage.passed? %>
    <%= t(".success", score: "<span class=\"test-passed\"><b>#{@test_passage}</b></span>").html_safe %>
    You have passed the test with the score: <span class="test-passed"><b><%= @test_passage %></b></span>
  <% else %>
    <%= t(".failure", score: "<span class=\"test-failed\"><b>#{@test_passage}</b></span>").html_safe %>
  <% end %>
</p>

<p>
  <%= link_to t(".back"), tests_path %>
</p>

app/views/test_passages/show.html.erb
<h1><%= t(".header", title: @test_passage.test.title) %></h1>

<%= timer(@test_passage).html_safe %>

<p>
  <%= t(".progress", current: @test_passage.current_question_number, total: @test_passage.questions_number ) %>
</p>

<%= render "shared/progress_bar",
           current_item: @test_passage.current_question_number,
           total_items: @test_passage.questions_number %>

<b>
  <%= @test_passage.current_question.body %>
</b>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object_id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to "Gist Question", gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit t(".next"), class: "btn btn-primary btn-next-question" %></p>
<% end %>