config/routes.rb
Rails.application.routes.draw do
  root "tests#index"

  devise_for :users, path: :gurus,
                               path_names: { sign_in: :login, sign_out: :logout }

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :show
  end
end

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: "resource-errors", data: { resource_id: resource.id } do %>
    <div id="error_explanation">
      <h2><%= t('.header', count: resource.errors.count) %>:</h2>

      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class(type) %>" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer font-small blue pt-4">
  <div class="container-fluid text-center text-md-left">
    <div class="row">
      <p>
        <%= current_year %>,
        Alexander Shcherbachenko,
        <%= github_url("MrAlejandro", "TestGuru") %>
      </p>
      <p>
      <p>
        TestGuru provides online testing service. It prints a quiz, one question and several answers to select.
        After submitting the test it prints the result back on the screen.<br>
        <%= link_to "Thinknetica", "http://www.thinknetica.com/", target: :blank %> online school TestGuru study project.
      </p>
    </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<div class="navbar navbar-light bg-light">
  <%= link_to "TestGuru", root_path, class: "navbar-brand" %>

  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t(".welcome", email: "<b>#{current_user.email}</b>").html_safe %> |
      <%= link_to t(".badges"), badges_path %> |
      <% if current_user.admin? %>
        <%= link_to t(".panel"), admin_tests_path %> |
      <% end %>
      <%= link_to t(".feedback"), new_feedback_path %> |
      <%= link_to t(".logout"), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t(".login"), new_user_session_path %> | <%= link_to t(".register"), new_user_registration_path %>
    <% end %>
  </span>
</div>

app/views/shared/_progress_bar.html.erb
<%= content_tag :div,
                class: "progress",
                data: { current_item: current_item, total_items: total_items } do %>
  <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
<% end %>