config/routes.rb
Rails.application.routes.draw do
  root "tests#index"

  devise_for :users, path: :gurus,
                               path_names: { sign_in: :login, sign_out: :logout }

  resources :feedbacks, only: %i[new create]

  resources :badges, only: :index

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :show
  end
end

app/models/question.rb
class Question < ApplicationRecord
  MAX_NUMBER_OF_ANSWERS = 4

  validates :body, presence: true

  has_many :gists
  has_many :answers
  belongs_to :test, optional: true

  def num_of_answers
    answers.count
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found_page

  before_action :set_test, only: %i[index new create]
  before_action :set_question, only: %i[update edit destroy]

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_question_path(@question), notice: t(".success")
    else
      render :new
    end
  end

  def edit
    @test = @question.test
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question), notice: t(".success")
    else
      render :edit
    end
  end

  def destroy
    @question.answers.destroy_all
    @question.destroy!
    redirect_to admin_test_path(@question.test)
  end

  private

  def set_test
    @test = Test.find(params[:test_id])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def render_not_found_page
    render file: "#{Rails.root}/public/404", status: :not_found
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_title(test, question)
    if question.persisted?
      "Edit '#{test.title}' question"
    else
      "Create '#{test.title}' question"
    end
  end
end

app/views/admin/questions/_form_fields.html.erb
<%= render "shared/errors", resource: @question %>

<p>
  <%= form.label :body %><br>
  <%= form.text_field :body %>
</p>

<div class="actions">
  <%= form.submit %>
</div>

app/views/admin/questions/_question.html.erb
<li>
  <%= question.body %><br>
  <%= link_to t(".show"), admin_question_path(question) %> |
  <%= link_to t(".edit"), edit_admin_question_path(question) %> |
  <%= link_to t(".delete"),
              admin_question_path(question),
              method: :delete,
              data: { confirm: t("delete?") } %>
</li>

app/views/admin/questions/edit.html.erb
<h1><%= question_title(@test, @question) %></h1>

<%= form_with model: [:admin, @question], local: true, method: :put do |form| %>
  <% render "form_fields", form: form %>
<% end %>

<%= link_to "Back", admin_question_path(@question) %>

app/views/admin/questions/index.html.erb
<h1><%= @test.title %></h1>

<ul>
  <%= render @questions %>
</ul>

<%= link_to "Tests list", tests_path %>
<%= link_to "Add question", new_test_question_path(@test) %>

app/views/admin/questions/new.html.erb
<h1><%= question_title(@test, @question) %></h1>

<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <% render "form_fields", form: form %>
<% end %>

<%= link_to "Back", admin_test_questions_path(@test) %>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title %> Question</h1>

<p>
  <%= @question.body %>
</p>

<h2>Answers:</h2>

<%= link_to "New answer", new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to "Edit", edit_admin_question_path(@question) %> |
<%= link_to "Back to test", admin_test_path(@question.test) %>